# Generated by Django 3.2.12 on 2022-03-04 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_refresh', models.DateTimeField(default=django.utils.timezone.now)),
                ('ipfs', models.CharField(default='', max_length=200)),
                ('abi', models.CharField(default='', max_length=10000)),
                ('address', models.CharField(default='', max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
